language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
# Force dist to trusty, as oraclejdk8 is not available on newer dists.
dist: trusty
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoRootReport
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches
after_success:
  - curl -s https://codecov.io/bash | bash -s - -f ./build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
